#!/bin/bash

# this is run in the bootstrap environment
set -e

if [ ! -d /mnt/archinstall ]; then
    archinstall --config /root/archinstall.json
fi
# select the user to set up by looking to find their home directory
user="$(find /mnt/archinstall/home -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | fzf -0 -1)"

# copy in wallpapers
background_dir="/mnt/archinstall/home/$user/Pictures/Wallpapers"
mkdir -p "$background_dir"
cp *.jpg "$background_dir"


# run post-install as user
post=/mnt/archinstall/usr/bin/post-install
cp post-install "$post"
HOME="/home/$user" arch-chroot -u "$user" /mnt/archinstall post-install
rm "$post"
