#!/bin/zsh

# this is run as the user under chroot in a newly provisioned arch environment
# guard, DO NOT run as root, run as main user
#
if [ "$(id -u)" -e 0 ]; then
    echo "this script should not be run as root"
    echo "this should also be run in a new chroot"
    exit 1
fi


# install yay
if ! type yay > /dev/null; then
    YAY="$DOTROOT/aur/yay"
    mkdir -p "$YAY"
    git clone https://aur.archlinux.org/yay-bin.git "$YAY"
    makepkg -siD "$YAY"
fi


# disable the systemd-boot menu
sudo bootctl set-timeout 0

# set bootsplash theme
yay -S --needed plymouth-theme-black-hud-git
sudo plymouth-set-default-theme -R black_hud

mkdir -p ~/Music/
systemctl --user enable mpd.service

DOTROOT=~/my
# create dot directory and load dotfiles
if [ ! -d "$DOTROOT" ]; then
    mkdir -p "$DOTROOT/toombs-caeman"
    git -C "$DOTROOT/toombs-caeman" clone https://github.com/toombs-caeman/dotfiles
fi

# reconfigure userspace
"$DOTROOT/toombs-caeman/dotfiles/bin/imbue"

clear
echo 'DONE!'
