lang = ['main',
 ['Definition',
  ['Identifier', 'G', 'r', 'a', 'm', 'm', 'a', 'r'],
  ['Sequence',
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g'],
   ['OneOrMore',
    ['Identifier', 'D', 'e', 'f', 'i', 'n', 'i', 't', 'i', 'o', 'n']],
   ['Identifier', 'E', 'n', 'd', 'O', 'f', 'F', 'i', 'l', 'e']]],
 ['Definition',
  ['Identifier', 'D', 'e', 'f', 'i', 'n', 'i', 't', 'i', 'o', 'n'],
  ['Sequence',
   ['Identifier', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r'],
   ['Identifier', 'L', 'E', 'F', 'T', 'A', 'R', 'R', 'O', 'W'],
   ['Identifier', 'E', 'x', 'p', 'r', 'e', 's', 's', 'i', 'o', 'n']]],
 ['Definition',
  ['Identifier', 'E', 'x', 'p', 'r', 'e', 's', 's', 'i', 'o', 'n'],
  ['Sequence',
   ['Identifier', 'S', 'e', 'q', 'u', 'e', 'n', 'c', 'e'],
   ['ZeroOrMore',
    ['Sequence',
     ['Identifier', 'S', 'L', 'A', 'S', 'H'],
     ['Identifier', 'S', 'e', 'q', 'u', 'e', 'n', 'c', 'e']]]]],
 ['Definition',
  ['Identifier', 'S', 'e', 'q', 'u', 'e', 'n', 'c', 'e'],
  ['ZeroOrMore', ['Identifier', 'P', 'r', 'e', 'f', 'i', 'x']]],
 ['Definition',
  ['Identifier', 'P', 'r', 'e', 'f', 'i', 'x'],
  ['Sequence',
   ['ZeroOrOne',
    ['Choice',
     ['Identifier', 'A', 'R', 'G'],
     ['Identifier', 'A', 'N', 'D'],
     ['Identifier', 'N', 'O', 'T']]],
   ['Identifier', 'S', 'u', 'f', 'f', 'i', 'x']]],
 ['Definition',
  ['Identifier', 'S', 'u', 'f', 'f', 'i', 'x'],
  ['Sequence',
   ['Identifier', 'P', 'r', 'i', 'm', 'a', 'r', 'y'],
   ['ZeroOrOne',
    ['Choice',
     ['Identifier', 'Q', 'U', 'E', 'S', 'T', 'I', 'O', 'N'],
     ['Identifier', 'S', 'T', 'A', 'R'],
     ['Identifier', 'P', 'L', 'U', 'S']]]]],
 ['Definition',
  ['Identifier', 'P', 'r', 'i', 'm', 'a', 'r', 'y'],
  ['Choice',
   ['Sequence',
    ['Identifier', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r'],
    ['NotLookahead',
     ['Identifier', 'L', 'E', 'F', 'T', 'A', 'R', 'R', 'O', 'W']]],
   ['Sequence',
    ['Identifier', 'O', 'P', 'E', 'N'],
    ['Identifier', 'E', 'x', 'p', 'r', 'e', 's', 's', 'i', 'o', 'n'],
    ['Identifier', 'C', 'L', 'O', 'S', 'E']],
   ['Identifier', 'L', 'i', 't', 'e', 'r', 'a', 'l'],
   ['Identifier', 'C', 'l', 'a', 's', 's'],
   ['Identifier', 'D', 'O', 'T']]],
 ['Definition',
  ['Identifier', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r'],
  ['Sequence',
   ['Identifier', 'I', 'd', 'e', 'n', 't', 'S', 't', 'a', 'r', 't'],
   ['ZeroOrMore', ['Identifier', 'I', 'd', 'e', 'n', 't', 'C', 'o', 'n', 't']],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'I', 'd', 'e', 'n', 't', 'S', 't', 'a', 'r', 't'],
  ['Class', ['Range', 'a', 'z'], ['Range', 'A', 'Z'], '_']],
 ['Definition',
  ['Identifier', 'I', 'd', 'e', 'n', 't', 'C', 'o', 'n', 't'],
  ['Choice',
   ['Identifier', 'I', 'd', 'e', 'n', 't', 'S', 't', 'a', 'r', 't'],
   ['Class', ['Range', '0', '9']]]],
 ['Definition',
  ['Identifier', 'L', 'i', 't', 'e', 'r', 'a', 'l'],
  ['Choice',
   ['Sequence',
    ['Class', "'"],
    ['ZeroOrMore',
     ['Sequence',
      ['NotLookahead', ['Class', "'"]],
      ['Identifier', 'C', 'h', 'a', 'r']]],
    ['Class', "'"],
    ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']],
   ['Sequence',
    ['Class', '"'],
    ['ZeroOrMore',
     ['Sequence',
      ['NotLookahead', ['Class', '"']],
      ['Identifier', 'C', 'h', 'a', 'r']]],
    ['Class', '"'],
    ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]]],
 ['Definition',
  ['Identifier', 'C', 'l', 'a', 's', 's'],
  ['Sequence',
   ['Literal', '['],
   ['ZeroOrMore',
    ['Sequence',
     ['NotLookahead', ['Literal', ']']],
     ['Identifier', 'R', 'a', 'n', 'g', 'e']]],
   ['Literal', ']'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'R', 'a', 'n', 'g', 'e'],
  ['Choice',
   ['Sequence',
    ['Identifier', 'C', 'h', 'a', 'r'],
    ['Literal', '-'],
    ['Identifier', 'C', 'h', 'a', 'r']],
   ['Identifier', 'C', 'h', 'a', 'r']]],
 ['Definition',
  ['Identifier', 'C', 'h', 'a', 'r'],
  ['Choice',
   ['Sequence',
    ['Literal', '\\', '\\'],
    ['Class', 'n', 'r', 't', "'", '"', '\\', '[', '\\', ']', '\\', '\\']],
   ['Sequence',
    ['Literal', '\\', '\\'],
    ['Class', ['Range', '0', '2']],
    ['Class', ['Range', '0', '7']],
    ['Class', ['Range', '0', '7']]],
   ['Sequence',
    ['Literal', '\\', '\\'],
    ['Class', ['Range', '0', '7']],
    ['ZeroOrOne', ['Class', ['Range', '0', '7']]]],
   ['Sequence', ['NotLookahead', ['Literal', '\\', '\\']], ['DOT']]]],
 ['Definition',
  ['Identifier', 'L', 'E', 'F', 'T', 'A', 'R', 'R', 'O', 'W'],
  ['Sequence',
   ['Literal', '<', '-'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'S', 'L', 'A', 'S', 'H'],
  ['Sequence',
   ['Literal', '/'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'A', 'R', 'G'],
  ['Sequence',
   ['Literal', '%'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'A', 'N', 'D'],
  ['Sequence',
   ['Literal', '&'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'N', 'O', 'T'],
  ['Sequence',
   ['Literal', '!'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'Q', 'U', 'E', 'S', 'T', 'I', 'O', 'N'],
  ['Sequence',
   ['Literal', '?'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'S', 'T', 'A', 'R'],
  ['Sequence',
   ['Literal', '*'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'P', 'L', 'U', 'S'],
  ['Sequence',
   ['Literal', '+'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'O', 'P', 'E', 'N'],
  ['Sequence',
   ['Literal', '('],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'C', 'L', 'O', 'S', 'E'],
  ['Sequence',
   ['Literal', ')'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'D', 'O', 'T'],
  ['Sequence',
   ['Literal', '.'],
   ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g']]],
 ['Definition',
  ['Identifier', 'S', 'p', 'a', 'c', 'i', 'n', 'g'],
  ['ZeroOrMore',
   ['Choice',
    ['Identifier', 'S', 'p', 'a', 'c', 'e'],
    ['Identifier', 'C', 'o', 'm', 'm', 'e', 'n', 't']]]],
 ['Definition',
  ['Identifier', 'C', 'o', 'm', 'm', 'e', 'n', 't'],
  ['Sequence',
   ['Literal', '#'],
   ['ZeroOrMore',
    ['Sequence',
     ['NotLookahead',
      ['Identifier', 'E', 'n', 'd', 'O', 'f', 'L', 'i', 'n', 'e']],
     ['DOT']]],
   ['Identifier', 'E', 'n', 'd', 'O', 'f', 'L', 'i', 'n', 'e']]],
 ['Definition',
  ['Identifier', 'S', 'p', 'a', 'c', 'e'],
  ['Choice',
   ['Literal', ' '],
   ['Literal', '\\', 't'],
   ['Identifier', 'E', 'n', 'd', 'O', 'f', 'L', 'i', 'n', 'e']]],
 ['Definition',
  ['Identifier', 'E', 'n', 'd', 'O', 'f', 'L', 'i', 'n', 'e'],
  ['Choice',
   ['Literal', '\\', 'r', '\\', 'n'],
   ['Literal', '\\', 'n'],
   ['Literal', '\\', 'r']]],
 ['Definition',
  ['Identifier', 'E', 'n', 'd', 'O', 'f', 'F', 'i', 'l', 'e'],
  ['NotLookahead', ['DOT']]]]
