#!/bin/bash

# set config dir if it isn't yet and get the config if it isn't there


infect_remote () {
: 'returns a command that will introduce the infect namespace to a remote host'
# TODO integrate with mosh
    echo bash -c "\"\$SHELL -i --rcfile <(echo "$(printf '%q' "$(declare -f infect)")")\""
}

prefix () {
: 'start an interactive subshell which prefixes every command with a given argument.
    $1 = command prefix
    $2 = prompt
'
    local cmd_prefix="${argv[0]}"
    local prompt="${argv[1]:-$cmd_prefix}"

    local old_complete_e="$(complete -p -E 2>/dev/null)"
    local old_complete_d="$(complete -p -D 2>/dev/null)"
    new_complete () {
        echo asdf
        $(complete -p "$cmd_prefix$1" 2>/dev/null|sed 's/complete/compgen/')
    }
    complete -D 'new_complete'
    complete -E 'new_complete'

    while read -e -p "$prompt" line; do
        $cmd_prefix$line
    done

    # clean up
    $old_complete_e
    $old_complete_d
    unset -f new_complete
    echo
}